// Autogenerated header test info
// Do not manually adjust this file
#ifndef PULSETRAINTEST_H
#define PULSETRAINTEST_H



namespace PulseTrainTest {

int32_t len_init_pulse_train=9;
int32_t init_pulse_train_data[9] = {-10, 10, -10, 30, 2, 2, 6, -10, 10};


int32_t num_test_cases=12;
int32_t t_start_arr[12] = {20, 25, 25, 19, 40, 60, 60, 15, 85, 100, 75, 80};
int32_t t_width_arr[12] = {5, 3, 5, 11, 5, 15, 25, 70, 20, 20, 25, 20};

int32_t new_train_data_0[10] = {-10, 10, 5, -5, 30, 2, 2, 6, -10, 10};
int32_t new_train_data_1[11] = {-10, 10, -5, 3, -2, 30, 2, 2, 6, -10, 10};
int32_t new_train_data_2[10] = {-10, 10, -5, 5, 30, 2, 2, 6, -10, 10};
int32_t new_train_data_3[9] = {-10, 10, 10, 30, 2, 2, 6, -10, 10};
int32_t new_train_data_4[9] = {-10, 10, -10, 30, 2, 2, 6, -10, 10};
int32_t new_train_data_5[10] = {-10, 10, -10, 30, 2, 2, 6, 5, -5, 10};
int32_t new_train_data_6[10] = {-10, 10, -10, 30, 2, 2, 6, 10, 10, -5};
int32_t new_train_data_7[10] = {-10, 10, 10, 30, 2, 2, 6, 10, 10, -5};
int32_t new_train_data_8[10] = {-10, 10, -10, 30, 2, 2, 6, -10, 10, 15};
int32_t new_train_data_9[11] = {-10, 10, -10, 30, 2, 2, 6, -10, 10, -10, 20};
int32_t new_train_data_10[11] = {-10, 10, -10, 30, 2, 2, 6, -5, 5, 10, 10};
int32_t new_train_data_11[10] = {-10, 10, -10, 30, 2, 2, 6, -10, 10, 10};

int32_t new_train_length_arr[12] = {10, 11, 10, 9, 9, 10, 10, 10, 10, 11, 11, 10};
int32_t* new_train_ptrs[12] = {&new_train_data_0[0], &new_train_data_1[0], &new_train_data_2[0], &new_train_data_3[0], &new_train_data_4[0], &new_train_data_5[0], &new_train_data_6[0], &new_train_data_7[0], &new_train_data_8[0], &new_train_data_9[0], &new_train_data_10[0], &new_train_data_11[0]} ;


}

#endif